services:
  crawler:
    build: .
    restart: always
    volumes:
      - crawler_data:/app/data
    networks:
      - app-network

volumes:
  crawler_data:

networks:
  app-network:
    driver: bridge
